services:
  app:
    container_name: avito-app
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: avito-app:1.0
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      GIN_MODE: ${GIN_MODE}
  migrator:
    container_name: avito-migrator
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    image: avito-migrator:1.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      GOOSE_DRIVER: ${GOOSE_DRIVER}
      GOOSE_MIGRATION_DIR: ${GOOSE_MIGRATION_DIR}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    restart: "no"
  postgres:
    container_name: avito-postgres
    restart: always
    image: postgres:17.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge



