// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Killazius/avito-pr/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockPRRepository is an autogenerated mock type for the PRRepository type
type MockPRRepository struct {
	mock.Mock
}

type MockPRRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPRRepository) EXPECT() *MockPRRepository_Expecter {
	return &MockPRRepository_Expecter{mock: &_m.Mock}
}

// AssignReviewer provides a mock function with given fields: ctx, prID, userID
func (_m *MockPRRepository) AssignReviewer(ctx context.Context, prID string, userID string) error {
	ret := _m.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssignReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPRRepository_AssignReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignReviewer'
type MockPRRepository_AssignReviewer_Call struct {
	*mock.Call
}

// AssignReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - userID string
func (_e *MockPRRepository_Expecter) AssignReviewer(ctx interface{}, prID interface{}, userID interface{}) *MockPRRepository_AssignReviewer_Call {
	return &MockPRRepository_AssignReviewer_Call{Call: _e.mock.On("AssignReviewer", ctx, prID, userID)}
}

func (_c *MockPRRepository_AssignReviewer_Call) Run(run func(ctx context.Context, prID string, userID string)) *MockPRRepository_AssignReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPRRepository_AssignReviewer_Call) Return(_a0 error) *MockPRRepository_AssignReviewer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPRRepository_AssignReviewer_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPRRepository_AssignReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePR provides a mock function with given fields: ctx, pr
func (_m *MockPRRepository) CreatePR(ctx context.Context, pr *models.PullRequest) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PullRequest) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPRRepository_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type MockPRRepository_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *models.PullRequest
func (_e *MockPRRepository_Expecter) CreatePR(ctx interface{}, pr interface{}) *MockPRRepository_CreatePR_Call {
	return &MockPRRepository_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, pr)}
}

func (_c *MockPRRepository_CreatePR_Call) Run(run func(ctx context.Context, pr *models.PullRequest)) *MockPRRepository_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PullRequest))
	})
	return _c
}

func (_c *MockPRRepository_CreatePR_Call) Return(_a0 error) *MockPRRepository_CreatePR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPRRepository_CreatePR_Call) RunAndReturn(run func(context.Context, *models.PullRequest) error) *MockPRRepository_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRByID provides a mock function with given fields: ctx, prID
func (_m *MockPRRepository) GetPRByID(ctx context.Context, prID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRByID")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPRRepository_GetPRByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRByID'
type MockPRRepository_GetPRByID_Call struct {
	*mock.Call
}

// GetPRByID is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPRRepository_Expecter) GetPRByID(ctx interface{}, prID interface{}) *MockPRRepository_GetPRByID_Call {
	return &MockPRRepository_GetPRByID_Call{Call: _e.mock.On("GetPRByID", ctx, prID)}
}

func (_c *MockPRRepository_GetPRByID_Call) Run(run func(ctx context.Context, prID string)) *MockPRRepository_GetPRByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPRRepository_GetPRByID_Call) Return(_a0 *models.PullRequest, _a1 error) *MockPRRepository_GetPRByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPRRepository_GetPRByID_Call) RunAndReturn(run func(context.Context, string) (*models.PullRequest, error)) *MockPRRepository_GetPRByID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPRAsMerged provides a mock function with given fields: ctx, prID, status, now
func (_m *MockPRRepository) MarkPRAsMerged(ctx context.Context, prID string, status models.PRStatus, now time.Time) error {
	ret := _m.Called(ctx, prID, status, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkPRAsMerged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.PRStatus, time.Time) error); ok {
		r0 = rf(ctx, prID, status, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPRRepository_MarkPRAsMerged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPRAsMerged'
type MockPRRepository_MarkPRAsMerged_Call struct {
	*mock.Call
}

// MarkPRAsMerged is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - status models.PRStatus
//   - now time.Time
func (_e *MockPRRepository_Expecter) MarkPRAsMerged(ctx interface{}, prID interface{}, status interface{}, now interface{}) *MockPRRepository_MarkPRAsMerged_Call {
	return &MockPRRepository_MarkPRAsMerged_Call{Call: _e.mock.On("MarkPRAsMerged", ctx, prID, status, now)}
}

func (_c *MockPRRepository_MarkPRAsMerged_Call) Run(run func(ctx context.Context, prID string, status models.PRStatus, now time.Time)) *MockPRRepository_MarkPRAsMerged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.PRStatus), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPRRepository_MarkPRAsMerged_Call) Return(_a0 error) *MockPRRepository_MarkPRAsMerged_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPRRepository_MarkPRAsMerged_Call) RunAndReturn(run func(context.Context, string, models.PRStatus, time.Time) error) *MockPRRepository_MarkPRAsMerged_Call {
	_c.Call.Return(run)
	return _c
}

// PRExists provides a mock function with given fields: ctx, prID
func (_m *MockPRRepository) PRExists(ctx context.Context, prID string) (bool, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for PRExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPRRepository_PRExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PRExists'
type MockPRRepository_PRExists_Call struct {
	*mock.Call
}

// PRExists is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPRRepository_Expecter) PRExists(ctx interface{}, prID interface{}) *MockPRRepository_PRExists_Call {
	return &MockPRRepository_PRExists_Call{Call: _e.mock.On("PRExists", ctx, prID)}
}

func (_c *MockPRRepository_PRExists_Call) Run(run func(ctx context.Context, prID string)) *MockPRRepository_PRExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPRRepository_PRExists_Call) Return(_a0 bool, _a1 error) *MockPRRepository_PRExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPRRepository_PRExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockPRRepository_PRExists_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveReviewer provides a mock function with given fields: ctx, prID, userID
func (_m *MockPRRepository) RemoveReviewer(ctx context.Context, prID string, userID string) error {
	ret := _m.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPRRepository_RemoveReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReviewer'
type MockPRRepository_RemoveReviewer_Call struct {
	*mock.Call
}

// RemoveReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - userID string
func (_e *MockPRRepository_Expecter) RemoveReviewer(ctx interface{}, prID interface{}, userID interface{}) *MockPRRepository_RemoveReviewer_Call {
	return &MockPRRepository_RemoveReviewer_Call{Call: _e.mock.On("RemoveReviewer", ctx, prID, userID)}
}

func (_c *MockPRRepository_RemoveReviewer_Call) Run(run func(ctx context.Context, prID string, userID string)) *MockPRRepository_RemoveReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPRRepository_RemoveReviewer_Call) Return(_a0 error) *MockPRRepository_RemoveReviewer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPRRepository_RemoveReviewer_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPRRepository_RemoveReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPRRepository creates a new instance of MockPRRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPRRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPRRepository {
	mock := &MockPRRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
