// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// RegisterRoutes provides a mock function with given fields: r
func (_m *MockHandler) RegisterRoutes(r gin.IRouter) {
	_m.Called(r)
}

// MockHandler_RegisterRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRoutes'
type MockHandler_RegisterRoutes_Call struct {
	*mock.Call
}

// RegisterRoutes is a helper method to define mock.On call
//   - r gin.IRouter
func (_e *MockHandler_Expecter) RegisterRoutes(r interface{}) *MockHandler_RegisterRoutes_Call {
	return &MockHandler_RegisterRoutes_Call{Call: _e.mock.On("RegisterRoutes", r)}
}

func (_c *MockHandler_RegisterRoutes_Call) Run(run func(r gin.IRouter)) *MockHandler_RegisterRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(gin.IRouter))
	})
	return _c
}

func (_c *MockHandler_RegisterRoutes_Call) Return() *MockHandler_RegisterRoutes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_RegisterRoutes_Call) RunAndReturn(run func(gin.IRouter)) *MockHandler_RegisterRoutes_Call {
	_c.Run(run)
	return _c
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
