// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/Killazius/avito-pr/internal/models"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetUserReviews provides a mock function with given fields: ctx, userID
func (_m *MockUserService) GetUserReviews(ctx context.Context, userID string) ([]*models.PullRequestShort, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReviews")
	}

	var r0 []*models.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PullRequestShort, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PullRequestShort); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetUserReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserReviews'
type MockUserService_GetUserReviews_Call struct {
	*mock.Call
}

// GetUserReviews is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserService_Expecter) GetUserReviews(ctx interface{}, userID interface{}) *MockUserService_GetUserReviews_Call {
	return &MockUserService_GetUserReviews_Call{Call: _e.mock.On("GetUserReviews", ctx, userID)}
}

func (_c *MockUserService_GetUserReviews_Call) Run(run func(ctx context.Context, userID string)) *MockUserService_GetUserReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetUserReviews_Call) Return(_a0 []*models.PullRequestShort, _a1 error) *MockUserService_GetUserReviews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserReviews_Call) RunAndReturn(run func(context.Context, string) ([]*models.PullRequestShort, error)) *MockUserService_GetUserReviews_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStatus provides a mock function with given fields: ctx, userID, isActive
func (_m *MockUserService) UpdateUserStatus(ctx context.Context, userID string, isActive bool) (*models.User, error) {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatus")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*models.User, error)); ok {
		return rf(ctx, userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *models.User); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_UpdateUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStatus'
type MockUserService_UpdateUserStatus_Call struct {
	*mock.Call
}

// UpdateUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *MockUserService_Expecter) UpdateUserStatus(ctx interface{}, userID interface{}, isActive interface{}) *MockUserService_UpdateUserStatus_Call {
	return &MockUserService_UpdateUserStatus_Call{Call: _e.mock.On("UpdateUserStatus", ctx, userID, isActive)}
}

func (_c *MockUserService_UpdateUserStatus_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *MockUserService_UpdateUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockUserService_UpdateUserStatus_Call) Return(_a0 *models.User, _a1 error) *MockUserService_UpdateUserStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_UpdateUserStatus_Call) RunAndReturn(run func(context.Context, string, bool) (*models.User, error)) *MockUserService_UpdateUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
