// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/Killazius/avito-pr/internal/models"
)

// MockPRService is an autogenerated mock type for the PRService type
type MockPRService struct {
	mock.Mock
}

type MockPRService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPRService) EXPECT() *MockPRService_Expecter {
	return &MockPRService_Expecter{mock: &_m.Mock}
}

// CreatePR provides a mock function with given fields: ctx, prID, prName, authorID
func (_m *MockPRService) CreatePR(ctx context.Context, prID string, prName string, authorID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID, prName, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID, prName, authorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID, prName, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, prID, prName, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPRService_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type MockPRService_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - prName string
//   - authorID string
func (_e *MockPRService_Expecter) CreatePR(ctx interface{}, prID interface{}, prName interface{}, authorID interface{}) *MockPRService_CreatePR_Call {
	return &MockPRService_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, prID, prName, authorID)}
}

func (_c *MockPRService_CreatePR_Call) Run(run func(ctx context.Context, prID string, prName string, authorID string)) *MockPRService_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPRService_CreatePR_Call) Return(_a0 *models.PullRequest, _a1 error) *MockPRService_CreatePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPRService_CreatePR_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.PullRequest, error)) *MockPRService_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// MergePR provides a mock function with given fields: ctx, prID
func (_m *MockPRService) MergePR(ctx context.Context, prID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPRService_MergePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePR'
type MockPRService_MergePR_Call struct {
	*mock.Call
}

// MergePR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPRService_Expecter) MergePR(ctx interface{}, prID interface{}) *MockPRService_MergePR_Call {
	return &MockPRService_MergePR_Call{Call: _e.mock.On("MergePR", ctx, prID)}
}

func (_c *MockPRService_MergePR_Call) Run(run func(ctx context.Context, prID string)) *MockPRService_MergePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPRService_MergePR_Call) Return(_a0 *models.PullRequest, _a1 error) *MockPRService_MergePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPRService_MergePR_Call) RunAndReturn(run func(context.Context, string) (*models.PullRequest, error)) *MockPRService_MergePR_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignReviewer provides a mock function with given fields: ctx, pullRequestID, oldUserID
func (_m *MockPRService) ReassignReviewer(ctx context.Context, pullRequestID string, oldUserID string) (*models.PullRequest, string, error) {
	ret := _m.Called(ctx, pullRequestID, oldUserID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 *models.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.PullRequest, string, error)); ok {
		return rf(ctx, pullRequestID, oldUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.PullRequest); ok {
		r0 = rf(ctx, pullRequestID, oldUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, pullRequestID, oldUserID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, pullRequestID, oldUserID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPRService_ReassignReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignReviewer'
type MockPRService_ReassignReviewer_Call struct {
	*mock.Call
}

// ReassignReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - pullRequestID string
//   - oldUserID string
func (_e *MockPRService_Expecter) ReassignReviewer(ctx interface{}, pullRequestID interface{}, oldUserID interface{}) *MockPRService_ReassignReviewer_Call {
	return &MockPRService_ReassignReviewer_Call{Call: _e.mock.On("ReassignReviewer", ctx, pullRequestID, oldUserID)}
}

func (_c *MockPRService_ReassignReviewer_Call) Run(run func(ctx context.Context, pullRequestID string, oldUserID string)) *MockPRService_ReassignReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPRService_ReassignReviewer_Call) Return(_a0 *models.PullRequest, _a1 string, _a2 error) *MockPRService_ReassignReviewer_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPRService_ReassignReviewer_Call) RunAndReturn(run func(context.Context, string, string) (*models.PullRequest, string, error)) *MockPRService_ReassignReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPRService creates a new instance of MockPRService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPRService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPRService {
	mock := &MockPRService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
