// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Killazius/avito-pr/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateOrUpdateUser provides a mock function with given fields: ctx, user, teamID
func (_m *MockUserRepository) CreateOrUpdateUser(ctx context.Context, user models.TeamMember, teamID string) error {
	ret := _m.Called(ctx, user, teamID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.TeamMember, string) error); ok {
		r0 = rf(ctx, user, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_CreateOrUpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateUser'
type MockUserRepository_CreateOrUpdateUser_Call struct {
	*mock.Call
}

// CreateOrUpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.TeamMember
//   - teamID string
func (_e *MockUserRepository_Expecter) CreateOrUpdateUser(ctx interface{}, user interface{}, teamID interface{}) *MockUserRepository_CreateOrUpdateUser_Call {
	return &MockUserRepository_CreateOrUpdateUser_Call{Call: _e.mock.On("CreateOrUpdateUser", ctx, user, teamID)}
}

func (_c *MockUserRepository_CreateOrUpdateUser_Call) Run(run func(ctx context.Context, user models.TeamMember, teamID string)) *MockUserRepository_CreateOrUpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.TeamMember), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_CreateOrUpdateUser_Call) Return(_a0 error) *MockUserRepository_CreateOrUpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_CreateOrUpdateUser_Call) RunAndReturn(run func(context.Context, models.TeamMember, string) error) *MockUserRepository_CreateOrUpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveTeamMembers provides a mock function with given fields: ctx, teamID, authorID, excludeIDs
func (_m *MockUserRepository) GetActiveTeamMembers(ctx context.Context, teamID string, authorID string, excludeIDs ...string) ([]*models.User, error) {
	_va := make([]interface{}, len(excludeIDs))
	for _i := range excludeIDs {
		_va[_i] = excludeIDs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, teamID, authorID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveTeamMembers")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...string) ([]*models.User, error)); ok {
		return rf(ctx, teamID, authorID, excludeIDs...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...string) []*models.User); ok {
		r0 = rf(ctx, teamID, authorID, excludeIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...string) error); ok {
		r1 = rf(ctx, teamID, authorID, excludeIDs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetActiveTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveTeamMembers'
type MockUserRepository_GetActiveTeamMembers_Call struct {
	*mock.Call
}

// GetActiveTeamMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - authorID string
//   - excludeIDs ...string
func (_e *MockUserRepository_Expecter) GetActiveTeamMembers(ctx interface{}, teamID interface{}, authorID interface{}, excludeIDs ...interface{}) *MockUserRepository_GetActiveTeamMembers_Call {
	return &MockUserRepository_GetActiveTeamMembers_Call{Call: _e.mock.On("GetActiveTeamMembers",
		append([]interface{}{ctx, teamID, authorID}, excludeIDs...)...)}
}

func (_c *MockUserRepository_GetActiveTeamMembers_Call) Run(run func(ctx context.Context, teamID string, authorID string, excludeIDs ...string)) *MockUserRepository_GetActiveTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockUserRepository_GetActiveTeamMembers_Call) Return(_a0 []*models.User, _a1 error) *MockUserRepository_GetActiveTeamMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetActiveTeamMembers_Call) RunAndReturn(run func(context.Context, string, string, ...string) ([]*models.User, error)) *MockUserRepository_GetActiveTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) GetUserByID(ctx context.Context, userID string) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserReviews provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) GetUserReviews(ctx context.Context, userID string) ([]*models.PullRequestShort, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReviews")
	}

	var r0 []*models.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PullRequestShort, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PullRequestShort); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserReviews'
type MockUserRepository_GetUserReviews_Call struct {
	*mock.Call
}

// GetUserReviews is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetUserReviews(ctx interface{}, userID interface{}) *MockUserRepository_GetUserReviews_Call {
	return &MockUserRepository_GetUserReviews_Call{Call: _e.mock.On("GetUserReviews", ctx, userID)}
}

func (_c *MockUserRepository_GetUserReviews_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_GetUserReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserReviews_Call) Return(_a0 []*models.PullRequestShort, _a1 error) *MockUserRepository_GetUserReviews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserReviews_Call) RunAndReturn(run func(context.Context, string) ([]*models.PullRequestShort, error)) *MockUserRepository_GetUserReviews_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIsActiveStatus provides a mock function with given fields: ctx, userID, isActive
func (_m *MockUserRepository) UpdateIsActiveStatus(ctx context.Context, userID string, isActive bool) error {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIsActiveStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateIsActiveStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIsActiveStatus'
type MockUserRepository_UpdateIsActiveStatus_Call struct {
	*mock.Call
}

// UpdateIsActiveStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *MockUserRepository_Expecter) UpdateIsActiveStatus(ctx interface{}, userID interface{}, isActive interface{}) *MockUserRepository_UpdateIsActiveStatus_Call {
	return &MockUserRepository_UpdateIsActiveStatus_Call{Call: _e.mock.On("UpdateIsActiveStatus", ctx, userID, isActive)}
}

func (_c *MockUserRepository_UpdateIsActiveStatus_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *MockUserRepository_UpdateIsActiveStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockUserRepository_UpdateIsActiveStatus_Call) Return(_a0 error) *MockUserRepository_UpdateIsActiveStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateIsActiveStatus_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockUserRepository_UpdateIsActiveStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
