// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Killazius/avito-pr/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockStatsRepository is an autogenerated mock type for the StatsRepository type
type MockStatsRepository struct {
	mock.Mock
}

type MockStatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsRepository) EXPECT() *MockStatsRepository_Expecter {
	return &MockStatsRepository_Expecter{mock: &_m.Mock}
}

// GetAssignmentsCount provides a mock function with given fields: ctx
func (_m *MockStatsRepository) GetAssignmentsCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAssignmentsCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_GetAssignmentsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssignmentsCount'
type MockStatsRepository_GetAssignmentsCount_Call struct {
	*mock.Call
}

// GetAssignmentsCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsRepository_Expecter) GetAssignmentsCount(ctx interface{}) *MockStatsRepository_GetAssignmentsCount_Call {
	return &MockStatsRepository_GetAssignmentsCount_Call{Call: _e.mock.On("GetAssignmentsCount", ctx)}
}

func (_c *MockStatsRepository_GetAssignmentsCount_Call) Run(run func(ctx context.Context)) *MockStatsRepository_GetAssignmentsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStatsRepository_GetAssignmentsCount_Call) Return(_a0 int, _a1 error) *MockStatsRepository_GetAssignmentsCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_GetAssignmentsCount_Call) RunAndReturn(run func(context.Context) (int, error)) *MockStatsRepository_GetAssignmentsCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRStats provides a mock function with given fields: ctx
func (_m *MockStatsRepository) GetPRStats(ctx context.Context) (*models.PRStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPRStats")
	}

	var r0 *models.PRStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.PRStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.PRStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PRStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_GetPRStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRStats'
type MockStatsRepository_GetPRStats_Call struct {
	*mock.Call
}

// GetPRStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsRepository_Expecter) GetPRStats(ctx interface{}) *MockStatsRepository_GetPRStats_Call {
	return &MockStatsRepository_GetPRStats_Call{Call: _e.mock.On("GetPRStats", ctx)}
}

func (_c *MockStatsRepository_GetPRStats_Call) Run(run func(ctx context.Context)) *MockStatsRepository_GetPRStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStatsRepository_GetPRStats_Call) Return(_a0 *models.PRStats, _a1 error) *MockStatsRepository_GetPRStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_GetPRStats_Call) RunAndReturn(run func(context.Context) (*models.PRStats, error)) *MockStatsRepository_GetPRStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamsCount provides a mock function with given fields: ctx
func (_m *MockStatsRepository) GetTeamsCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamsCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_GetTeamsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamsCount'
type MockStatsRepository_GetTeamsCount_Call struct {
	*mock.Call
}

// GetTeamsCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsRepository_Expecter) GetTeamsCount(ctx interface{}) *MockStatsRepository_GetTeamsCount_Call {
	return &MockStatsRepository_GetTeamsCount_Call{Call: _e.mock.On("GetTeamsCount", ctx)}
}

func (_c *MockStatsRepository_GetTeamsCount_Call) Run(run func(ctx context.Context)) *MockStatsRepository_GetTeamsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStatsRepository_GetTeamsCount_Call) Return(_a0 int, _a1 error) *MockStatsRepository_GetTeamsCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_GetTeamsCount_Call) RunAndReturn(run func(context.Context) (int, error)) *MockStatsRepository_GetTeamsCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersStats provides a mock function with given fields: ctx
func (_m *MockStatsRepository) GetUsersStats(ctx context.Context) (*models.UsersStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersStats")
	}

	var r0 *models.UsersStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.UsersStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.UsersStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UsersStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_GetUsersStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersStats'
type MockStatsRepository_GetUsersStats_Call struct {
	*mock.Call
}

// GetUsersStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsRepository_Expecter) GetUsersStats(ctx interface{}) *MockStatsRepository_GetUsersStats_Call {
	return &MockStatsRepository_GetUsersStats_Call{Call: _e.mock.On("GetUsersStats", ctx)}
}

func (_c *MockStatsRepository_GetUsersStats_Call) Run(run func(ctx context.Context)) *MockStatsRepository_GetUsersStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStatsRepository_GetUsersStats_Call) Return(_a0 *models.UsersStats, _a1 error) *MockStatsRepository_GetUsersStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_GetUsersStats_Call) RunAndReturn(run func(context.Context) (*models.UsersStats, error)) *MockStatsRepository_GetUsersStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsRepository creates a new instance of MockStatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsRepository {
	mock := &MockStatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
