// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/Killazius/avito-pr/internal/models"
)

// MockStatsService is an autogenerated mock type for the StatsService type
type MockStatsService struct {
	mock.Mock
}

type MockStatsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsService) EXPECT() *MockStatsService_Expecter {
	return &MockStatsService_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function with given fields: ctx
func (_m *MockStatsService) GetStats(ctx context.Context) (*models.Stats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *models.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.Stats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.Stats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Stats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsService_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockStatsService_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsService_Expecter) GetStats(ctx interface{}) *MockStatsService_GetStats_Call {
	return &MockStatsService_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockStatsService_GetStats_Call) Run(run func(ctx context.Context)) *MockStatsService_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStatsService_GetStats_Call) Return(_a0 *models.Stats, _a1 error) *MockStatsService_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsService_GetStats_Call) RunAndReturn(run func(context.Context) (*models.Stats, error)) *MockStatsService_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsService creates a new instance of MockStatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsService {
	mock := &MockStatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
