// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Killazius/avito-pr/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function with given fields: ctx, teamName
func (_m *MockTeamRepository) CreateTeam(ctx context.Context, teamName string) error {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, teamName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamRepository_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamRepository_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTeamRepository_Expecter) CreateTeam(ctx interface{}, teamName interface{}) *MockTeamRepository_CreateTeam_Call {
	return &MockTeamRepository_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, teamName)}
}

func (_c *MockTeamRepository_CreateTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockTeamRepository_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamRepository_CreateTeam_Call) Return(_a0 error) *MockTeamRepository_CreateTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_CreateTeam_Call) RunAndReturn(run func(context.Context, string) error) *MockTeamRepository_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamWithMembers provides a mock function with given fields: ctx, name
func (_m *MockTeamRepository) GetTeamWithMembers(ctx context.Context, name string) (*models.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamWithMembers")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_GetTeamWithMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamWithMembers'
type MockTeamRepository_GetTeamWithMembers_Call struct {
	*mock.Call
}

// GetTeamWithMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamRepository_Expecter) GetTeamWithMembers(ctx interface{}, name interface{}) *MockTeamRepository_GetTeamWithMembers_Call {
	return &MockTeamRepository_GetTeamWithMembers_Call{Call: _e.mock.On("GetTeamWithMembers", ctx, name)}
}

func (_c *MockTeamRepository_GetTeamWithMembers_Call) Run(run func(ctx context.Context, name string)) *MockTeamRepository_GetTeamWithMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamWithMembers_Call) Return(_a0 *models.Team, _a1 error) *MockTeamRepository_GetTeamWithMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetTeamWithMembers_Call) RunAndReturn(run func(context.Context, string) (*models.Team, error)) *MockTeamRepository_GetTeamWithMembers_Call {
	_c.Call.Return(run)
	return _c
}

// TeamExists provides a mock function with given fields: ctx, name
func (_m *MockTeamRepository) TeamExists(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for TeamExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_TeamExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamExists'
type MockTeamRepository_TeamExists_Call struct {
	*mock.Call
}

// TeamExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamRepository_Expecter) TeamExists(ctx interface{}, name interface{}) *MockTeamRepository_TeamExists_Call {
	return &MockTeamRepository_TeamExists_Call{Call: _e.mock.On("TeamExists", ctx, name)}
}

func (_c *MockTeamRepository_TeamExists_Call) Run(run func(ctx context.Context, name string)) *MockTeamRepository_TeamExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamRepository_TeamExists_Call) Return(_a0 bool, _a1 error) *MockTeamRepository_TeamExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_TeamExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTeamRepository_TeamExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
